# Generated by Django 3.1.5 on 2021-01-23 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devrestapp', '0002_auto_20210123_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='deptno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devrestapp.department'),
        ),
        migrations.AddField(
            model_name='employees',
            name='office_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devrestapp.office'),
        ),
    ]
