# Generated by Django 3.1.5 on 2021-01-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devrestapp', '0003_auto_20210123_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='contactno',
            field=models.CharField(max_length=20),
        ),
    ]
