# Generated by Django 3.1.5 on 2021-01-29 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devrestapp', '0004_auto_20210128_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employees',
            new_name='Employee',
        ),
    ]
