# Generated by Django 3.1.5 on 2021-02-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devrestapp', '0005_auto_20210129_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='empemail',
            field=models.EmailField(default='example@gmail.com', max_length=30),
        ),
    ]
