# Generated by Django 3.1.5 on 2021-02-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devrestapp', '0006_employee_empemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='empemail',
            new_name='email_address',
        ),
        migrations.AlterField(
            model_name='employee',
            name='contactno',
            field=models.CharField(max_length=10),
        ),
    ]
