# Generated by Django 3.1.5 on 2021-02-07 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devrestapp', '0007_auto_20210207_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='contactno',
            new_name='phone_number',
        ),
    ]
